SELECT
"public".contacts_full."CONTACTID" AS contact_id,
"public".contacts_full."1st DOB" AS "Client Birthdate",
"public".contacts_full."1st Name" AS "Client Name",
"public".contacts_full."1st Pronunciation" AS "Client Pronunciation",
"public".contacts_full."1st Retired" AS "Client is Retired?",
"public".contacts_full."2nd DOB" AS "Co-Client Birthdate",
"public".contacts_full."2nd Name" AS "Co-Client Name",
"public".contacts_full."2nd Pronunciation" AS "Co-Client Pronunciation",
"public".contacts_full."2nd Retired" AS "Co-Client is Retired?",
"public".contacts_full."Company" AS "Company Name",
"public".contacts_full."Department",
"public".contacts_full."First Name",
"public".contacts_full."Middle Name",
"public".contacts_full."Name Prefix" AS "Salutation",
"public".contacts_full."Name Suffix" AS "Suffix",
"public".contacts_full."Owner" AS "Client Owner",
"public".contacts_full."Record Manager",
"public".contacts_full."Referred By",
"public".contacts_full."Salutation" AS "Nickname",
"public".contacts_full."Spouse",
"public".contacts_full."Title" AS "Client Title",
"public".contacts_full."Web Site",
"public".contacts_full."Client Type",
"public".contacts_full."Star Rating",
"public".contacts_full."Bene Date" AS "Last Bene Review",
"public".contacts_full."Contact Salutation",
"public".contacts_full."OktoContact" AS "Ok to Contact",
"public".contacts_full."Commission Schedule",
"public".contacts_full."Bio Information",
"public".contacts_full."1st Annual Income" AS "Client Job Inc",
"public".contacts_full."1st Income Other" AS "Other Inc.",
"public".contacts_full."1st Income Pension" AS "Pension Inc",
"public".contacts_full."1st Income SSI" AS "Client SSI Inc.",
"public".contacts_full."1st Job Description" AS "Client Job Description",
"public".contacts_full."1st Occupation" AS "Client Occupation",
"public".contacts_full."1st SSN" AS "Client SSN",
"public".contacts_full."2nd Annual Income" AS "Co-Client Job Inc",
"public".contacts_full."2nd Income Other" AS "Co-Client Other Inc.",
"public".contacts_full."2nd Income Pension" AS "Co-Client Pension Inc.",
"public".contacts_full."2nd Income SSI" AS "Co-Client SSI Inc.",
"public".contacts_full."2nd Job Description" AS "Co-Client Job Description",
"public".contacts_full."2nd Occupation" AS "Co-Client Occupation",
"public".contacts_full."2nd SSN" AS "Co-Client SSN",
"public".contacts_full."Quit Date",
"public".contacts_full."Income Type",
"public".contacts_full."Sign-up date",
"public".contacts_full."AUM",
"public".contacts_full."AUM Date",
"public".contacts_full."Annual Revenue",
"public".contacts_full."PreferredCommunicationMethod" AS "Preferred Communication Method",
"public".contacts_full."Current Overall Allocation" AS "CurrentOverallAllocation",
"public".contacts_full."Target Overall Allocation" AS "TargetOverallAllocation",
"public".contacts_full."Excluded Assets",
"public".contacts_full."Custodian",
"public".contacts_full."ADV",
"public".contacts_full."Fee Schedule",
"public".contacts_full."Fee Start Date",
"public".contacts_full."Investment Start Date",
"public".contacts_full."Billing Account",
"public".contacts_full."Tax Bracket" AS "TaxBracket",
"public".contacts_full."Client Restrictions",
"public".contacts_full."Investable Non-Chinook Assets",
"public".contacts_full."Overall Investment Strategy",
"public".contacts_full."Personal Use Property",
"public".contacts_full."Tax Planning Loss Carry Date",
"public".contacts_full."Tax Planning Loss Carry Document",
"public".contacts_full."Tax Planning Loss Carry Expert",
"public".contacts_full."Tax Planning Loss Carry Summary",
"public".contacts_full."Loss Carry Forward LT",
"public".contacts_full."Loss Carry Forward ST",
"public".contacts_full."Loss Carry Forward Total",
"public".contacts_full."Last Client Contact",
"public".contacts_full."Last Client Meeting",
"public".contacts_full."Last Date Referral",
"public".contacts_full."Last Date Referral Notes",
"public".contacts_full."Last Email" AS "Last E-mail",
"public".contacts_full."Last Email Notes",
"public".contacts_full."Last In-Person Review",
"public".contacts_full."Last In-Person Review Notes" AS "Last In-Person Notes",
"public".contacts_full."Last Meeting",
"public".contacts_full."Last Phone Review",
"public".contacts_full."Last Phone Review Notes",
"public".contacts_full."Last Name",
"public".contacts_full."Last Review Offered",
"public".contacts_full."Last Review Offered Notes",
"public".contacts_full."Left Message",
"public".contacts_full."Left Message Notes",
"CONTACTID"||'household' AS household_id,
"public".contacts_full."Administrator",
"public".contacts_full."ID/Status",
"public".contacts_full."Lead Contact",
"public".contacts_full."Managed By",
"public".contacts_full."Master Number" as "Master No"
FROM
"public"."contacts_full"
