SELECT
"public".contacts.contact_id,
"public".contacts."Firm ",
"public".contacts."T3",
"public".contacts."Mnthly",
"public".contacts.impct,
"public".contacts."FndJly05",
"public".contacts."Alisha",
"public".contacts."Tier",
"public".contacts."Type of Advisor",
"public".contacts."Website",
"public".contacts."2006 Assets",
"public".contacts."AUM ",
"public".contacts."# of Accounts",
"public".contacts."Avg. Account Size",
"public".contacts."Amt. Invested",
"public".contacts."Notes",
"public".contacts."NTF",
"public".contacts."TF",
"public".contacts."FOF",
"public".contacts."FOF+",
"public".contacts."TIPS",
"public".contacts."DLM/EM",
"public".contacts."NonUS Fixed",
"public".contacts."NonUS Fixed NonUSD",
"public".contacts."CMDTY",
"public".contacts."FI Multi Stgy",
"public".contacts."Floating Rate",
"public".contacts."HY",
"public".contacts."CPI Hedge Interest",
"public".contacts."Core FI",
"public".contacts."S&P500",
"public".contacts."F48",
"public".contacts."EMN Call",
"public".contacts."DSS Call",
"public".contacts."BBG Call",
"public".contacts."Early Adopters ",
"public".contacts."FO ?",
"public".contacts."TAMP ?",
"public".contacts."No $",
"public".contacts."<2",
"public".contacts."2 - 10",
"public".contacts."10 - 25",
"public".contacts."25-99",
"public".contacts.">99",
"public".contacts."Region",
"public".contacts."Funds Used",
"public".contacts."First Name 1",
"public".contacts."Job Title 1",
"public".contacts."Last Name 1"
FROM
"public".contacts
